Use `InnerHTML` mixin for `innerHTML` definition
jsdom/jsdom pull request #2981
Opened 2020-05-22 16:14 UTC by ExE-Boss

<https://github.com/w3c/DOM-Parsing/issues/21> has been resolved, so this can be updated.

I’ve kept the implementations in `Element‑impl.js` and `ShadowRoot‑impl.js`, as they have little actual overlap.

2020-05-22 17:52 UTC, TimothyGu commented
Hmm, the implementations are merged in the spec though. I think it would be a good idea to merge them.

2021-03-15 22:59 UTC, ExE-Boss commented on lib/jsdom/living/domparsing/InnerHTML-impl.js
> +};
This matches what’s done for `NonElementParentNodeImpl`: <https://github.com/jsdom/jsdom/blob/69b0205ed4cdafe94f9ffea519e00dcc67e17f1f/lib/jsdom/living/nodes/NonElementParentNode-impl.js#L3-L7>

2021-03-28 17:39 UTC, TimothyGu approved these changes

2021-03-28 17:41 UTC, TimothyGu requested changes
Actually sorry, could you merge the implementations of innerHTML from Element and ShadowRoot in a manner similar to the [spec](https://w3c.github.io/DOM-Parsing/#dom-innerhtml-innerhtml)? I know the spec is not the cleanest but I'd rather us stick to it.

2021-04-02 17:07 UTC, TimothyGu commented on lib/jsdom/living/domparsing/InnerHTML-impl.js
> +    }
This isn't quite right. The spec makes a distinction between "context element" and "context object".

```suggestion
    const contextElement = isShadowRoot(this) ? this.host : this;
    const fragment = parseFragment(markup, contextObject);

    let contextObject = this;
    if (this.nodeType === NODE_TYPE.ELEMENT_NODE && this.localName === "template" && this.namespaceURI === HTML_NS) {
      contextObject = contextObject._templateContents;
    }
```

2021-04-03 02:43 UTC, TimothyGu approved these changes

2021-04-03 02:43 UTC, merged