Convert `NamedPropertiesTracker` to a class
jsdom/jsdom pull request #3138
Opened 2021-03-10 13:09 UTC by ExE-Boss

Extracted from: <https://github.com/jsdom/jsdom/pull/2835>

2021-03-10 23:22 UTC, TimothyGu commented on lib/jsdom/living/named-properties-window.js
> +  if ("contentWindow" in element && !idlUtils.hasOwn(element, "contentWindow")) {
Let's try to keep idlUtils usage to a minimum outside of wrapping/unwrapping.

2021-03-10 23:22 UTC, TimothyGu commented on lib/jsdom/named-properties-tracker.js
> +
Can you remove this comment? It duplicates the existing documentation.

2021-03-10 23:22 UTC, TimothyGu commented on lib/jsdom/named-properties-tracker.js
> +  // eslint-disable-next-line no-use-before-define
Can we move NamedPropertiesTracker to before this function?

2021-03-13 00:36 UTC, domenic requested changes

2021-03-13 00:36 UTC, domenic commented on lib/jsdom/living/named-properties-window.js
> +  if ("contentWindow" in element && !hasOwn(element, "contentWindow")) {
Let's not add a separate util for this. Instead just undo these changes; they're not related to this PR and we're happy with the current style.

2021-03-13 00:36 UTC, domenic commented on lib/jsdom/living/named-properties-window.js
> +/**
No jsdoc please. I'll see if we can add a lint rule prohibiting it...

2021-03-13 00:36 UTC, domenic commented on lib/jsdom/named-properties-tracker.js
> +  /**
Instead of changing the jsdoc let's just remove it all.

2021-03-13 00:36 UTC, domenic commented on lib/jsdom/named-properties-tracker.js
> +    // https://github.com/petkaantonov/bluebird/blob/3e36fc861ac5795193ba37935333eb6ef3716390/src/util.js#L177
We can delete this; it turns out not to have been an issue.

2021-03-27 21:16 UTC, domenic commented
This isn't worth the time; interacting with you is exhausting and often ends in you making accusatory _italicized_ or **bolded** comments about how I maintain the project. So since this particular change brings little value, I'm not going to accept it.

2021-03-27 21:16 UTC, closed without merging