Update update-a-style-block algorithm
jsdom/jsdom pull request #3180
Opened 2021-04-21 13:26 UTC by Qendolin

The algorithm has changed, the style element is no longer required to have a browsing context. 

https://html.spec.whatwg.org/multipage/semantics.html#update-a-style-block

FIxes #3179

2021-04-25 14:48 UTC, Qendolin commented
@TimothyGu can you review?

2021-05-06 15:17 UTC, Qendolin commented
Sorry if I am being annoying but it has been over two weeks. 
@domenic

2021-05-06 16:09 UTC, domenic commented
You are being annoying. We work on jsdom in our free time, which is rare, and I personally am experiencing some burnout on the project. This is not helpful.

2021-05-06 18:07 UTC, Qendolin commented
Thank you for the response, if you don't have time then I don't mind waiting. I just wanted some confirmation that this PR is not being ignored or something.

2021-05-08 17:04 UTC, domenic approved these changes

2021-05-08 17:04 UTC, domenic requested changes
Can you test the contents of the sheet? Does it contain any rules?

2021-05-09 19:54 UTC, domenic approved these changes
LGTM as long as the test passes.

2021-05-09 20:32 UTC, domenic commented
Hmm, yeah, this new test isn't passing. I'm glad I asked for it.

I'd suggest getting a dev environment set up that allows you to run the tests; then you should be able to figure out how to make them pass.

2021-05-09 23:02 UTC, Qendolin commented
The code was already correct but not the test. I used the deprecated (but probably still used) `rules` property instead of `cssRules`. (I also noticed that JSDOM does not run any tests from `/css/cssom/` 🤔)

2021-05-09 23:56 UTC, domenic commented
No, the test was correct. (It passed in Chrome and Firefox.) The code needs fixing.

2021-05-10 12:10 UTC, Qendolin commented
The test cannot pass as long as [cssom's CSSStyleSheet](https://github.com/NV/CSSOM/blob/97bee0949153ecb3295eccf98da2be79b7269e2f/lib/CSSStyleSheet.js#L13-L16) does not support deprecated properties / methods. Or am I missing something?

2021-05-10 15:21 UTC, domenic commented
It works elsewhere in jsdom...

2021-05-10 16:53 UTC, Qendolin commented
That is not true, although `.rules` is used in many test, non of them are enabled.

This includes all tests at `test\web-platform-tests\tests\css\cssom\`, especially `test\web-platform-tests\tests\css\cssom\CSSStyleSheet.html`

How did I come to this conclusion? 
- I searched for `.rules` in all .html and .js test files.
- Looked at the folder, i.e.: `test\web-platform-tests\tests\css\cssom\`
- And ran `yarn test --fgrep css/cssom`
- None executed (only `css/cssom-view`)
- Add `DIR: css/cssom` in `to-run.yml`
- So many errors that I couldn't read them

You can also run this example:
```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM(`<!DOCTYPE html><style id="mystyle">p {color: red;}</style>`);

const sheet = dom.window.document.getElementById("mystyle").sheet
console.log("Rules: %o", sheet.rules);
console.log("Css Rules: %o", sheet.cssRules);
```

And you'll see that `sheet.rules` is undefined.

2021-06-16 22:48 UTC, Klinter4802 requested changes
#

2021-07-08 11:10 UTC, Qendolin commented
If someone can provide me with an example of `.rules` working with JSDOM then I'ld be happy to fix my changes but as far as I can tell `.rules` never worked and all tests for it are disabled. 
If `.rules` is not supported in JSDOM and there are no other issues with my changes then please merge this PR. 
If you (you meaning contributes with write access) do not have time or do not intend to spend any more time on this PR then I'll close it.

2021-07-22 12:37 UTC, closed without merging